apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rdma-sriov-dp-ds
  namespace: kube-system
  labels:
    k8s-app: rdma-sriov-dp-ds
spec:
  selector:
    matchLabels:
      k8s-app: rdma-sriov-dp-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: rdma-sriov-dp-ds
    spec:
      hostNetwork: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - image: ccr.ccs.tencentyun.com/houminwei/k8s-rdma-sriov-dev-plugin:v0.0.4
          name: k8s-rdma-sriov-dp-ds
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: config
              mountPath: /k8s-rdma-sriov-dev-plugin
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: config
          configMap:
            name: rdma-devices
            items:
              - key: config.json
                path: config.json